package inventory

// Consumables : Inventory list of available Consumables for Party Inventory
func Consumables() Inventory {
	return []Item {
		{0xBD, "Tonic"},
		{0xBE, "Mid Tonic"},
		{0xBF, "Full Tonic"},
		{0xC0, "Ether"},
		{0xC1, "Mid Ether"},
		{0xC2, "Full Ether"},
		{0xC3, "Elixir"},
		{0xC4, "HyperEther"},
		{0xC5, "MegaElixir"},
		{0xC6, "Heal"},
		{0xC7, "Revive"},
		{0xC8, "Shelter"},
		{0xC9, "Power Meal"},
		{0xCA, "Lapis"},
		{0xCB, "Barrier"},
		{0xCC, "Shield"},
		{0xCD, "Power Tab"},
		{0xCE, "Magic Tab"},
		{0xCF, "Speed Tab"},
		{0xD0, "Petal"},
		{0xD1, "Fang"},
		{0xD2, "Horn"},
		{0xD3, "Feather"},
		{0xD4, "Seed"},
		{0xD5, "Bike Key"},
		{0xD6, "Pendant"},
		{0xD7, "Gate Key"},
		{0xD8, "PrismShard"},
		{0xD9, "C. Trigger"},
		{0xDA, "Tools"},
		{0xDB, "Jerky"},
		{0xDC, "DreamStone"},
		{0xDD, "Race Log"},
		{0xDE, "Moon Stone"},
		{0xDF, "Sun Stone"},
		{0xE0, "Ruby Knife"},
		{0xE1, "Yakra Key"},
		{0xE2, "Clone"},
		{0xE3, "Toma's Pop"},
		{0xE4, "2 Petals"},
		{0xE5, "2 Fangs"},
		{0xE6, "2 Horns"},
		{0xE7, "2 Feathers"},
	}
}