package inventory

// Relics : Inventory list of available Relics for All Characters
func Relics() Inventory{
	return []Item{
		{0x95, "Bandana"},
		{0x96, "Ribbon"},
		{0x97, "PowerGlove"},
		{0x98, "Defender"},
		{0x99, "Magic Scarf"},
		{0x9A, "Amulet"},
		{0x9B, "Dash Ring"},
		{0x9C, "Hit Ring"},
		{0x9D, "Power Ring"},
		{0x9E, "Magic Ring"},
		{0x9F, "Wall Ring"},
		{0xA0, "SilverErng"},
		{0xA1, "Gold Erng"},
		{0xA2, "SilverStud"},
		{0xA3, "Gold Stud"},
		{0xA4, "SightScope"},
		{0xA5, "Charm Top"},
		{0xA6, "Rage Band"},
		{0xA7, "Frenzy Band"},
		{0xA8, "Third Eye"},
		{0xA9, "wallet"},
		{0xAA, "Green Dream"},
		{0xAB, "Berserker"},
		{0xAC, "Power scarf"},
		{0xAD, "Speed Belt"},
		{0xAE, "Black Rock"},
		{0xAF, "Blue Rock"},
		{0xB0, "Silver Rock"},
		{0xB1, "White Rock"},
		{0xB2, "Gold Rock"},
		{0xB3, "Hero Medal"},
		{0xB4, "Muscle Ring"},
		{0xB5, "Flea Vest"},
		{0xB6, "Magic Seal"},
		{0xB7, "Power Seal"},
		{0xB8, "Relic"},
		{0xB9, "SeraphSong"},
		{0xBA, "Sun Shades"},
		{0xBB, "Prism Specs"},
	}
}
